version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dream_shops_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=dream_shops_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
